# Generated by Django 6.0.2 on 2026-03-09 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('committed_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
